### ISSUE TITLE
spell magic lock/unlock

### ISSUE THREAD

**Issue by andrtechno** [polserver/ModernDistro#100]
`if (cast_on.IsA(POLCLASS_CONTAINER))`
need change to
`if (!cast_on.IsA(POLCLASS_CONTAINER))`

**Comment by andrtechno** [comment]
I also think you need to add a check for POLCLASS_SPELLBOOK

**Comment by Admin-Yukiko** [comment]
Fixed in commit #e3751dbfdc9ed671de789db4cdf20a031d1fa354
There were quite a few things that were improved and/or changed.
Read the commit comments for a complete list of changes.

**Comment by andrtechno** [comment]
IsLeather not work meybe IsLeatherContainer

**Comment by andrtechno** [comment]
@Admin-Yukiko
