### ISSUE TITLE
spell gate unknown object

### ISSUE THREAD

**Issue by andrtechno** [polserver/ModernDistro#102]
what is this? 0x1aa07, 0x160ff objects

https://github.com/polserver/ModernDistro/blob/master/pkg/skills/magery/spells/circle7/gate.src#L100-L130

**Comment by andrtechno** [comment]
and yet, if you open the portal, and then restart the server, the portal will stand forever.

**Comment by andrtechno** [comment]
and this object 0x16100 (runebook const) is also not correct in all scripts

**Comment by andrtechno** [comment]
same thing in recall

**Comment by andrtechno** [comment]
I will not create a new issue, just write here

https://github.com/polserver/ModernDistro/blob/master/pkg/utils/timedScripts/subScripts/magery/endInvisibility.src#L15
need change Paralysis to Invisibility

**Comment by Admin-Yukiko** [comment]
"I will not create a new issue, just write here

https://github.com/polserver/ModernDistro/blob/master/pkg/utils/timedScripts/subScripts/magery/endInvisibility.src#L15
need change Paralysis to Invisibility"

Changed.

Changed SaveOnExit to 0 for Item 0xF6C.
Changed runebook ObjType number from 0x16100 to 0x22C5 in gate and recall scripts.

**Comment by andrtechno** [comment]
> what is this? 0x1aa07, 0x160ff objects

wtf? =)

**Comment by Admin-Yukiko** [comment]
Interdicts, ObjType 0x1aa07, should have been removed. They were for a system not in the Distro that allowed restricting fast travel.
ObjType 0x160ff was the ObjType for the old static house sign.
I appreciate your bug reports but please include the file names in which you find the issues. As this was a multiple-topic issue report I had to search for those hex numbers.
