### ISSUE TITLE
spellweaving

### ISSUE THREAD

**Issue by andrtechno** [polserver/ModernDistro#103]
semi-working package

**Comment by Admin-Yukiko** [comment]
Yes. That is why the package was disabled. The developer who was working on it stopped work and has not resumed yet. Anyone who would like to develop that package for the Distro is welcome to do so.

**Comment by che666** [comment]
https://uo.com/wiki/ultima-online-wiki/skills/spellweaving/

**Comment by sigmantium** [comment]
I think at the time the core did not support the AOS extended item properties which some of the spells affected. The focus shifted towards those being implemented in the core and this was put on hold until they were done (they are now at least). When I have time I may look into finishing this off, but may not be until I complete my studies at the end of the year.
