### ISSUE TITLE
Missing chargeUpkeep script

### ISSUE THREAD

**Issue by AsYlum-** [polserver/ModernDistro#33]
In scripts/misc/logon.src in function RestoreMods around line 470 we can find:

`start_script(":combat:chargeUpkeep", parms);`

but this script does not exist in modernDistro package.

also there  are calls through start_script inside pkg/systems/combat/include/equip.inc

**Comment by Admin-Yukiko** [comment]
I will look into start_script(":combat:chargeUpkeep", parms). It's probably a leftover from the old combat system. This is an example of why any logon, logoff or reconnect script that is central to a package should be in that package. The main logon script should only have general functions and not be complicated with package-specific functions to be performed during logging on or off.
"also there are calls through start_script inside pkg/systems/combat/include/equip.inc". Thanks. I will look at that also.

**Comment by Admin-Yukiko** [comment]
Finally fixed this issue. I am sorry it took me so long. I guess I need to visit the repo's website more often.
