### ISSUE TITLE
Making daggers don't rise skill

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#58]
Making daggers don't take blacksmith up.

**Comment by Admin-Yukiko** [comment]
I am working on this. I will return to it later after my frustration subsides :)

**Comment by Admin-Yukiko** [comment]
Fixed in commit #022f246ef455e48060251fb3ec1bd66f82b9b584

**Comment by StrobelArtesao** [comment]
> Fixed in commit #022f246ef455e48060251fb3ec1bd66f82b9b584

Thanks for it, my friend!
