### ISSUE TITLE
tinkertraps.ecl does not exists

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#59]
When trying to open a traped container such as a treasure chest it does not trigger the trap. In POL cmd it gives this messege

Warning! pkg/skills/tinkering/tinkerTraps.ecl does not exist!
Exception caught while loading script pkg/skills/tinkering/tinkerTraps.ecl: Unable to open pkg/skills/tinkering/tinkerTraps.ecl for reading.
Unable to read script 'pkg/skills/tinkering/tinkerTraps.ecl'

**Comment by Admin-Yukiko** [comment]
This was fixed when I changed tinkering to utilize the traps package for crafting traps. Unfortunately, I have been lazy in closing fixed issues.
