### ISSUE TITLE
Treasure Chest not adding items

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#60]
When using treasurechest spawn system, it is unable to spawn items in ti. Instead it spawns a key

in POL cmd it gives a messege like the one below for each item it can't spawn
syslog [pkg/tools/gmtools/spawnTest.ecl]: Unable to create sapphire on wooden chest. Error= Could not insert item into container.

**Comment by Admin-Yukiko** [comment]
Again, I am late closing a fixed issue. I "recently" worked on the gmtools package and when I tested the chest spawner it worked for me. So, I am closing this issue. By the way, I owe a big "Thank you" to Strobel for his tireless testing of the Distro.
