### ISSUE TITLE
Crates and Chests 

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#65]
Every interactive (openable) chest and crate in the world has a key in it. 

Treasure chests are being created as regular chests with a key in it

**Comment by StrobelArtesao** [comment]
traps doesn't work in containers.

There is a script runing all the time ( canInsert.ecl) in pol. Can it be related to those problems?

**Comment by Admin-Yukiko** [comment]
Traps should now work on containers.
I'll have to decide what, if anything, to do about lockable containers being created with a key. Right now they have an onCreate script that automatically adds the key.
I will begin looking at treasure chests. I had to get traps working first. I am certain I'll need to deal with the "key created in container" issue when I handle treasure chests.

**Comment by Admin-Yukiko** [comment]
I stopped keys being created in spawned chests. And, with recent updates to GM tools to use the traps package, I think this issue can be closed.
