### ISSUE TITLE
Damage indication is not showing on animation

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#66]
There is no visual damage indicationen when you hit some npc or player or if you get hit by it

**Comment by StrobelArtesao** [comment]
I've fixed this by changing the "if ( attacker.cmdlevel >= 2 )" to "if ( attacker.cmdlevel >= 0 )" in mainHitScript00.src


it became this:

function DamageInfo(attacker, defender, basedamage, rawdamage)
	if ( attacker.cmdlevel >= 0 )
		PrintTextAbovePrivate(attacker, "Rawdamage:"+rawdamage+"  Base:"+basedamage, attacker);
	endif
	if ( defender.cmdlevel >= 0 )
		PrintTextAbovePrivate(attacker, "Rawdamage:"+rawdamage+"  Base:"+basedamage, defender);
	endif
endfunction

**Comment by turleypol** [comment]
Is in your combat.cfg SendDamagePacket enabled?
