### ISSUE TITLE
pkg/items/magic/powerorb.ecl does not exist!

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#68]
A warning wile loading things in POL is 
WARNING! pkg/items/magic/powerorb.ecl does not exist!

**Comment by Admin-Yukiko** [comment]
That was fixed in [url=https://github.com/polserver/ModernDistro/commit/022f246ef455e48060251fb3ec1bd66f82b9b584]this commit[/url].)
