### ISSUE TITLE
Camping is not working 

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#76]
It can be that I don't know how it works. Can't make a fire and unroll the bedroll

**Comment by Admin-Yukiko** [comment]
I tested camping. I started with my camping skill set to 50. I eventually was able to start a campfire with kindling. Admittedly my skill rose to 51.5 when I got the kindling to ignite. Once the kindling was burning I was able to use the bedroll. Then the logout countdown started and I was logged out when it reached 0. So, for me, camping seemed to work as expected. I'll leave this issue open for now.

**Comment by Admin-Yukiko** [comment]
I have tested camping again and it appears to work for me. So I am going to close this issue.
