### ISSUE TITLE
Some sounds are off or missing

### ISSUE THREAD

**Issue by StrobelArtesao** [polserver/ModernDistro#84]
I've noticed many sounds are "missing" or "different", like the  pickaxe sound is a "punch" sound instead of "tchktchktchk". The sounds of putting things in your backpack are missing. Like throwing som coins in your bag or getting ore while mining. Nothing makes sound. The sound of smelting ores is a "bubbly boiling" sound and not a flames/forge sound.

**Comment by Admin-Yukiko** [comment]
Fixed in latest commit.
