### ISSUE TITLE
:timedScript: > spiritspeak

### ISSUE THREAD

**Issue by andrtechno** [polserver/ModernDistro#91]
`mobile.GrantPrivilege("hearghosts");`

```
//need change to
GrantPrivilege(mobile, "hearghosts");
```

**Comment by Admin-Yukiko** [comment]
I don't know why that line was in there. The Core doesn't provide a GrantPrivilige() method. I removed it. The following line, `mobile.Enable("hearghosts");` will accomplish the desired outcome.
